comission_proposal:
  description: >
    Study the 2024 French budget. 
    Try to find where cut in expenses can be made to match
    a total save of 60 billion euros in comparison with 2024 budget.
    The ministries to study are: Finance, Interior, Justice, Education, Health, Defense, Culture, Sports, Ecological Transition, Labour
  expected_output: >
    Two 2025 budgets proposals. 
    The first proposal will left-wing. The second proposal will be right_wing.
    Each proposal is a table with a row for each ministry of France with the following columns:
    - proposal 2025 budget and 2024 budget for this ministry in euros
    - the difference in percentage with 2024 budget
    - a sentence to explain this proposal
    Add a row for total spending cuts at the end of this table.
    Each proposal also containes a second table to detail the changes in tax income for the upper class, middle class and business tax. Detail the choices in a paragraph.
    Formatted as markdown
  agent: finance_commission_president

decide_and_report_task:
  description: >
    Review the two budget proposal of the finance comission.
    Choose the budget proposal that matches the best the needs of France for 2025.
  expected_output: >
    A report containing the selected budget and the reason why chose this budget and rejected the second budget.
    The report must also contain one sentence for each ministry to detail why you chose this budget over the other.
    Formatted as markdown
  agent: prime_minister

